name: Code quality check
run-name: Check code quality with linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Linters:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout
        uses: actions/checkout@v4 # Указана актуальная версия

      # Шаг 2: Установка JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Шаг 3: Настройка Gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v2 # Актуальная версия Gradle Setup Action
        with:
          gradle-version: '8.9' # Укажите используемую версию Gradle
          cache-disabled: true # Если кэширование не нужно, оставьте true

      # Шаг 4: Запуск Detekt
      - name: Detekt
        shell: bash
        run: ./gradlew detekt

      # Шаг 5: Публикация отчета Detekt
      - name: Publish Checkstyle Report
        uses: Juuxel/publish-checkstyle-report@v1.0.0
        with:
          reports: '**/build/reports/detekt.xml'
