name: Code quality check and Build Release
run-name: Check code quality with linter and build release APK
on: [push]

jobs:
    Linters:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Set up Gradle
              uses: gradle/actions/setup-gradle@v4
              with:
                  cache-disabled: false

            - name: Run Detekt Linter
              shell: bash
              run: ./gradlew detekt
              env:
                  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
                  RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
                  RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}

    BuildRelease:
        runs-on: ubuntu-latest
        needs: Linters
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Set up Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Decrypt Keystore
              env:
                  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
                  RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
                  RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
                  RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
              run: |
                  echo "Decrypting keystore file..."
                  mkdir -p ~/.android
                  echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > ~/.android/release.keystore

            - name: Build Release APK
              run: ./gradlew assembleRelease
              env:
                  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
                  RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
                  RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}

            - name: Upload APK Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: release-apk
                  path: app/build/outputs/apk/release/*.apk
